### ISSUE TITLE
Replace LiveData with StateFlow

### ISSUE THREAD

**Issue by Dement0** [Dement0/repeatcard#103]
We should replace LiveData usage with StateFlow.

**Comment by guuilp** [comment]
Hey @Dement0, could you assign that to me?

**Comment by Dement0** [comment]
> Hey @Dement0, could you assign that to me?

Hey @guuilp sure, go for it!
Thank you for your interest in the project :rocket: 

If you have any questions just jump into the Discord channel :left_speech_bubble:
