### ISSUE TITLE
fix/buttons

### ISSUE THREAD

**Issue by Dement0** [Dement0/repeatcard#110]
We should have the same styling (margins,  dimensions etc..) for all buttons in the app.

As a reference it would be nice to have the style of the save button that we have in `QuizScreen`.

For the buttons in the `QuestionDetailScreen` maybe we can create a separate style as they are horrible right now :rofl:

**Comment by sidram05** [comment]
I would like to work on this,  Please assign this to me, thanks!

**Comment by Dement0** [comment]
> I would like to work on this, Please assign this to me, thanks!

Hey @sidram05 , thanks for your interest in the project!

Sure, assigning this issue to you. If you have and questions please join the Discord server in order to prevent unnecessary work :+1:

**Comment by sidram05** [comment]
Sure will do..

**Comment by sidram05** [comment]
Hi @Dement0 ,

You would like to have the **green "Save" button** styling to be implemented to the **"QuestionDetail screen"**(which currently have red button), is my understanding right ?

![GreenButton](https://user-images.githubusercontent.com/38928563/96679490-5f6d6300-1339-11eb-9011-94d5b520366b.JPG)

**Comment by Dement0** [comment]
> Hi @Dement0 ,
> 
> You would like to have the **green "Save" button** styling to be implemented to the **"QuestionDetail screen"**(which currently have red button), is my understanding right ?
> 
> ![GreenButton](https://user-images.githubusercontent.com/38928563/96679490-5f6d6300-1339-11eb-9011-94d5b520366b.JPG)

@sidram05 Exactly, also we should figure out something for the next and previous buttons! Don't forget to check the screen to add a Directory too!

**Comment by Dement0** [comment]
Sorry @sidram05 but this issue needs to be fixed soon so I'm self assigning this! Let me know if you want to work on another issue, thanks.
