### ISSUE TITLE
Fix "No Flashcards Yet" Error

### ISSUE THREAD

**Issue by Dement0** [Dement0/repeatcard#118]
When we're in a directory that has no Flashcards and we add one, "No Flashcards Yet" text is still visible instead of becoming invisible. Might be a problem with `StateFlow` that we used in the corresponding ViewModel.

**Comment by gitrahulgit** [comment]
I want to work on it

**Comment by Dement0** [comment]
> I want to work on it

Hi @gitrahulgit thanks for your interest in the issue. Sure, I'm assigning it to you.

You can join our Discord channel if you have any questions :smile:
