### ISSUE TITLE
Remove logs

### ISSUE THREAD

**Issue by Dement0** [Dement0/repeatcard#90]
We should remove the logs as it's not a requested feature.

**Comment by Giancarmine** [comment]
Hi, can you please assign me?

**Comment by Dement0** [comment]
Sure, thank you for your interest in the project! Just write your request
under the issue so I can see your name and assign it.

Feel free to ask questions if you get stuck.

Have a nice day,

Ilker

Il giorno ven 9 ott 2020 alle 20:49 Giancarmine <notifications@github.com>
ha scritto:

**Comment by Kardelio** [comment]
Can i just ask on this ticket...
Does this ticket mean to remove the "Logs" functionality as in the LogScreen fragment and everything related to it?
Or does it mean something else?

Im interested in picking this up and getting involved but just confused by the meaning of the ticket. Thanks 😄

**Comment by Dement0** [comment]
> Can i just ask on this ticket...
> Does this ticket mean to remove the "Logs" functionality as in the LogScreen fragment and everything related to it?
> Or does it mean something else?
> AKA the notifications (bell) tab?
> 
> Im interested in picking this up and getting involved but just confused by the meaning of the ticket. Thanks smile

Hi there! Sorry for being ambiguous, I guess I was tired while writing the issue :smile: 

I was intending to remove Logs functionality as you've pointed out. It was something that I've implemented to practice MVVM architecture, but I realize that it's not useful so maybe the app will be better without it!

That being said, I'm planning to implement something more fancy like Profile or Settings feature instead of Logs. Thus, it would be better to get rid of Logs to make space for the new features!

I hope this clarifies the issue a bit more. Let me know if I can help you with anything and if you're still interested in! :rocket: 

BTW, thank you for being interested in the project!

**Comment by Kardelio** [comment]
Yeh that makes sense, would you mind if I pick this up then?

**Comment by Dement0** [comment]
> Yeh that makes sense, would you mind if I pick this up then?

Sure thing, go ahead!

**Comment by Kardelio** [comment]
PR: #99 
Please let me know if what i have done is incorrect happy to change it 😄

**Comment by Dement0** [comment]
> PR: #99
> Please let me know if what i have done is incorrect happy to change it smile

Thank you for the contribution! :rocket:

**Comment by Dement0** [comment]
Resolved by #99
